name: geo app workflow
on:
    workflow_dispatch:
    push:

permissions:
  id-token: write
  contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Repository checkout
          uses: actions/checkout@v7

        - name: List files
          run: ls -al

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run test
          run: python -m pytest

        - name: Upload results
          uses: actions/upload-artifact@v7
          with:
            name: test-results
            path: htmlcov

    build:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Repo checkout
              uses: actions/checkout@v7

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build docker iamge and push
              uses: docker/build-push-action@v7
              with:
                context: .
                push: true
                tags: mdfaiz01/geo-app:v3

    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Azure Login
          uses: azure/login@v3
          with:
            client-id: "f9e3f06d-96f5-4cf4-bc30-8054cbadd412"
            tenant-id: "a2baa2da-e78a-412a-8972-fd9cd0686b29"
            subscription-id: "4a37656d-b956-416d-af8e-44e4f08f0a52"
            mask-client-id: false

        - name: Deploy to Azure Container Instance
          run: |
              az container create \
              --resource-group geo-app-rg \
              --name geo-app \
              --image mdfaiz01/geo-app:v3 \
              --cpu 1 \
              --memory 2 \
              --ports 5000 \
              --registry-login-server docker.io \
              --registry-username ${{ vars.DOCKERHUB_USERNAME }} \
              --registry-password ${{ secrets.DOCKERHUB_TOKEN }}




            




        


